Thinking in react
reactjs/mn.react.dev pull request #345
Opened 2023-05-05 18:21 UTC by munkhjin0223

#338

2023-05-06 00:52 UTC, munkhjin0223 commented on src/content/learn/thinking-in-react.md
> -* **CSS**--consider what you would make class selectors for. (However, components are a bit less granular.)
Энийг яг юу гэж орчуулахаа сайн мэдэхгүй байна

2023-05-06 01:06 UTC, munkhjin0223 commented on src/content/learn/thinking-in-react.md
> -* **CSS**--consider what you would make class selectors for. (However, components are a bit less granular.)
Энийг сайн орчуулж чаддаггүй ээ

2023-05-08 08:56 UTC, munkhjin0223 commented on src/components/MDX/ExpandableCallout.tsx
> -    title: 'Pitfall',
Энийг орчуулах хэрэг байна уу?

2023-05-08 09:04 UTC, Zorig commented on src/components/MDX/ExpandableCallout.tsx
> -    title: 'Pitfall',
Хэрэггүй байх

2023-05-08 09:24 UTC, Zorig requested changes
Өөр дээрээ ажиллуулж үзэж байгаа юу зарим текст урагшаа хойшоо болсон байна `prettier` ажиллуулах команд ажиллуулж хялбар засах боломжтой шүү

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +## Алхам 1: UI-аа компонентын шатлал болгон салгая {/*step-1-break-the-ui-into-a-component-hierarchy*/}
UI ыг компонент болгон хуваая эсвэл салгая гэх болов уу

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +Эхлээд бүх компонент болон дэд компонентуудыг mockup загварын дагуу зурж тэдгээрийг нэрлэнэ. Хэрвээ та дизайнертайгаа ажиллаж байгаа бол тэд аль хэдийн диэайн зурдаг хэрэгсэл дээрээ нэрлэсэн байж маг
Typo

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +* **Програмчилалын**--Шинээр функц болон объект үүсгэхдээ нэгэн ижил текник ашиглаарай. Нэг санал болгох текник нь [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibilit
Typo

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +Хэрхээ таны JSON маш сайн бүтэцлэгдсэн бол таны UI компонентуудтай шууд холбогдож ажиллаж чадна. Энэ нь UI болон өгөгдлийн загварууд (data model) ижил бүтэцтэй байх хэрэгтэй шалтгаан юм.
Typo

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +2. `SearchBar` (цэнхэр) хэрэглэгчийн оролтын хүлээж авах.
Typo

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +Одоо mockup дизайн дээрх компонентүүдийг шаталсан бүтцээр харуулцгаая.
Нэмээд 
> компонент доторх компонент нь доорх догол мөрөнд харагдана 

Гэх мэтээр

2023-05-08 09:24 UTC, Zorig commented on src/content/learn/thinking-in-react.md
> +Одоо энэ жишээн програм-д байгаа бүх өгөгдлийн талаар бодоцгооё:
Typo

2023-05-08 13:08 UTC, Zorig approved these changes

2023-05-08 13:09 UTC, merged