Quick Start translation
reactjs/mn.react.dev pull request #349
Opened 2023-05-11 11:15 UTC by gracexnn

2023-05-11 13:56 UTC, Zorig commented on src/content/learn/index.md
> +React component нь markup буцаадаг Javascript функц юм:
JavaScript

2023-05-11 14:08 UTC, gracexnn commented on src/content/learn/index.md
> +    <button>Товчлуур</button>
За. Өөрчлөөд ахиад commit хийхүү ?

2023-05-15 13:27 UTC, Zorig requested changes

2023-05-15 13:27 UTC, Zorig commented on src/content/learn/index.md
> +React таны компонентийн функцийг дахин дуудна. Товчин дээр дарах үед тоо нь "1" болно, дараа нь '2' болно гэх мэт.
`1` бас `2`

2023-05-17 00:47 UTC, merged